set current schema vpcrzkh1;

CREATE TABLE usrgrp (
      usrprf CHAR(10) NOT NULL,
      grpprf CHAR(10) NOT NULL,
      PRIMARY KEY (usrprf)
    );


INSERT INTO usrgrp VALUES ('USER01', 'ITGRP');
INSERT INTO usrgrp VALUES ('USER02', 'ITGRP');
INSERT INTO usrgrp VALUES ('USER03', 'ITGRP');
INSERT INTO usrgrp VALUES ('USER04', 'FINGRP');
INSERT INTO usrgrp VALUES ('USER05', 'FINGRP');
INSERT INTO usrgrp VALUES ('USER06', 'FINGRP');
INSERT INTO usrgrp VALUES ('USER07', 'FINGRP');
INSERT INTO usrgrp VALUES ('USER08', 'OPSGRP');
INSERT INTO usrgrp VALUES ('USER09', 'OPSGRP');
INSERT INTO usrgrp VALUES ('USER10', 'OPSGRP');
INSERT INTO usrgrp VALUES ('USER11', 'SALESGRP');
INSERT INTO usrgrp VALUES ('USER12', 'SALESGRP');
INSERT INTO usrgrp VALUES ('USER13', 'MKTGRP');
INSERT INTO usrgrp VALUES ('USER14', 'HRGRP');
INSERT INTO usrgrp VALUES ('USER15', 'HRGRP');
INSERT INTO usrgrp VALUES ('USER16', 'ITGRP');
INSERT INTO usrgrp VALUES ('USER17', 'ITGRP');
INSERT INTO usrgrp VALUES ('USER18', 'ITGRP');
INSERT INTO usrgrp VALUES ('USER19', 'FINGRP');
INSERT INTO usrgrp VALUES ('USER20', 'FINGRP');
INSERT INTO usrgrp VALUES ('USER21', 'FINGRP');
INSERT INTO usrgrp VALUES ('USER22', 'FINGRP');
INSERT INTO usrgrp VALUES ('USER23', 'OPSGRP');
INSERT INTO usrgrp VALUES ('USER24', 'OPSGRP');
INSERT INTO usrgrp VALUES ('USER25', 'OPSGRP');
INSERT INTO usrgrp VALUES ('USER26', 'SALESGRP');
INSERT INTO usrgrp VALUES ('USER27', 'SALESGRP');
INSERT INTO usrgrp VALUES ('USER28', 'MKTGRP');
INSERT INTO usrgrp VALUES ('USER29', 'HRGRP');
INSERT INTO usrgrp VALUES ('USER30', 'HRGRP');
INSERT INTO usrgrp VALUES ('USER31', 'HRGRP');
INSERT INTO usrgrp VALUES ('USER32', 'OPSFRP');
INSERT INTO usrgrp VALUES ('USER33', 'OPSFRP');
INSERT INTO usrgrp VALUES ('USER34', 'OPSGRP');
INSERT INTO usrgrp VALUES ('USER35', 'OPSGRP');

select * from usrgrp;

DELETE FROM usrgrp;

