set current schema vpcrzkh1;

__ display the packed_decimal from the flat file
SELECT SUBSTR(flatfld, 1, 4) AS itemcode, 
       SUBSTR(flatfld, 5, 3) AS rawpackedpos,
       INTERPRET(BINARY(SUBSTR(flatfld, 5, 3)) AS DECIMAL(5, 2)) as valpackedpos,
       SUBSTR(flatfld, 8, 3) AS rawpackedneg,
       INTERPRET(BINARY(SUBSTR(flatfld, 8, 3)) AS DECIMAL(5, 2)) as valpackedneg,
       SUBSTR(flatfld, 11, 5) AS rawzonedpos,
       INTERPRET(BINARY(SUBSTR(flatfld, 11, 5)) AS NUMERIC(5, 2)) as valzonedpos,
       SUBSTR(flatfld, 16, 5) AS rawzonedneg,
       INTERPRET(BINARY(SUBSTR(flatfld, 16, 5)) AS NUMERIC(5, 2)) as valzonedneg
  FROM flatfile;       

 
 SELECT SUBSTR(FLATFLD, 1, 4) AS ITEM_CODE,
INTERPRET(BINARY(SUBSTR(FLATFLD, 5, 3)) AS DECIMAL(5, 2)) AS VAL_PACKED_POS,
INTERPRET(BINARY(SUBSTR(FLATFLD, 8, 3)) AS DECIMAL(5, 2)) AS VAL_PACKED_NEG,
INTERPRET(BINARY(SUBSTR(FLATFLD, 11, 5)) AS NUMERIC(5, 2)) AS VAL_ZONED_POS,
INTERPRET(BINARY(SUBSTR(FLATFLD, 16, 5)) AS NUMERIC(5, 2)) AS VAL_ZONED_NEG
FROM FLATFILE;    


-- SELECT
  -- CAST(SUBSTR(FLATFLD, 1, 10) AS CHAR(10) CCSID 37) AS ITEM_CODE,
  -- INTERPRET(CAST(SUBSTR(FLATFLD, 5, 3) AS BINARY(3)) AS NUMERIC(5, 2)) AS PACKED_POS,
  -- INTERPRET(CAST(SUBSTR(FLATFLD, 8, 3) AS BINARY(3)) AS NUMERIC(5, 2)) AS PACKED_NEG,
  -- INTERPRET(CAST(SUBSTR(FLATFLD, 11, 7) AS BINARY(5)) AS DECIMAL(5, 2)) AS ZONED_POS,
  -- INTERPRET(CAST(SUBSTR(FLATFLD, 16, 7) AS BINARY(5)) AS DECIMAL(5, 2)) AS ZONED_NEG
  -- from flatfile;
  