set current schema vpcrzkh1;

  
-- can be used to query from flatfile
select
SUBSTR(FLATFLD, 1, 10) AS WS_MSG_TEXT,
INTERPRET(BINARY(SUBSTR(FLATFLD, 11, 7)) AS NUMERIC(7, 2)) AS WS_MSG_ZONED_POS,
INTERPRET(BINARY(SUBSTR(FLATFLD, 18, 7)) AS NUMERIC(7, 2)) AS WS_MSG_ZONED_NEG,
INTERPRET(BINARY(SUBSTR(FLATFLD, 25, 4)) AS DECIMAL(7, 2)) AS WS_MSG_PACKED_POS,
INTERPRET(BINARY(SUBSTR(FLATFLD, 29, 4)) AS DECIMAL(7, 2)) AS WS_MSG_PACKED_NEG,
INTERPRET(BINARY(SUBSTR(FLATFLD, 33, 4)) AS INTEGER) AS WS_MSG_BINARY_POS,
INTERPRET(BINARY(SUBSTR(FLATFLD, 37, 4)) AS INTEGER) AS WS_MSG_BINARY_NEG
from flatfile;

-- this is better as this could be used to query flatfile or message from data queue
select
  CAST(SUBSTR(FLATFLD, 1, 10) AS CHAR(10) CCSID 37) AS TEXT,
  INTERPRET(CAST(SUBSTR(FLATFLD, 11, 7) AS BINARY(7)) AS NUMERIC(7, 2)) AS ZONED_POS,
  INTERPRET(CAST(SUBSTR(FLATFLD, 18, 7) AS BINARY(7)) AS NUMERIC(7, 2)) AS ZONED_NEG,
  INTERPRET(CAST(SUBSTR(FLATFLD, 25, 4) AS BINARY(4)) AS DECIMAL(7, 2)) AS PACKED_POS,
  INTERPRET(CAST(SUBSTR(FLATFLD, 29, 4) AS BINARY(4)) AS DECIMAL(7, 2)) AS PACKED_NEG,
  INTERPRET(CAST(SUBSTR(FLATFLD, 33, 4) AS BINARY(4)) AS INTEGER) AS BINARY_POS,
  INTERPRET(CAST(SUBSTR(FLATFLD, 37, 4) AS BINARY(4)) AS INTEGER) AS BINARY_NEG
  from flatfile;
  