--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	26-01-26 15:14:51 
--  Relational Database:       	PUB400 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM" ; 
  
CREATE FUNCTION SYSTOOLS.GENERATE_SPREADSHEET ( 
	PATH_NAME DBCLOB(900) CCSID 1200 , 
	SPREADSHEET_QUERY VARCHAR(4000) FOR SBCS DATA DEFAULT  NULL  , 
	LIBRARY_NAME VARCHAR(10) FOR SBCS DATA DEFAULT  NULL  , 
	FILE_NAME VARCHAR(10) FOR SBCS DATA DEFAULT  NULL  , 
	SPREADSHEET_TYPE VARCHAR(4) FOR SBCS DATA DEFAULT  'csv'  , 
	COLUMN_HEADINGS VARCHAR(6) FOR SBCS DATA DEFAULT  'NONE'  , 
	SPREADSHEET_QUERY_IFS DBCLOB(5120) CCSID 1200 DEFAULT  NULL  , 
	OVERWRITE VARCHAR(7) FOR SBCS DATA DEFAULT  'REPLACE'  , 
	STARTING_SHEET INTEGER DEFAULT  NULL  , 
	STARTING_ROW INTEGER DEFAULT  NULL  , 
	STARTING_COLUMN VARCHAR(3) FOR SBCS DATA DEFAULT  NULL  , 
	KILL_DAEMON VARCHAR(3) FOR SBCS DATA DEFAULT  'NO'  ) 
	RETURNS INTEGER   
	LANGUAGE SQL 
	SPECIFIC SYSTOOLS.GENSPREAD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	NOT FENCED 
	SYSTEM_TIME SENSITIVE NO 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QSYS2 , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX , 
	USRPRF = *USER   
	BEGIN 
DECLARE CMD_TEXT VARCHAR ( 10000 ) FOR SBCS DATA ; 
DECLARE CLDOWNLOAD_RESULT INTEGER ; 
DECLARE ACS_JAR_COUNT INTEGER ; 
DECLARE LOCAL_SQLCODE INTEGER ; 
DECLARE LOCAL_SQLSTATE CHAR ( 5 ) FOR SBCS DATA ; 
DECLARE V_MESSAGE_TEXT VARCHAR ( 2000 ) FOR SBCS DATA ; 
DECLARE V_FAILURE_TEXT VARCHAR ( 2000 ) FOR SBCS DATA ; 
DECLARE FILE_EXISTS INTEGER ; 
DECLARE OVERRIDE_COUNT INTEGER ; 
DECLARE OVERRIDE_FAILURE INTEGER DEFAULT 0 ; 
DECLARE IFS_FILE_CCSID INTEGER ; 
DECLARE IFS_FILE_COUNT INTEGER ; 
DECLARE ACS_LEVEL_1198 INTEGER ; 
DECLARE ACS_LEVEL_1199 INTEGER ; 
DECLARE ACS_LEVEL_1198_PTF VARCHAR ( 7 ) FOR SBCS DATA ; 
DECLARE ACS_LEVEL_1199_PTF VARCHAR ( 7 ) FOR SBCS DATA ; 
DECLARE OPERATING_SYSTEM_RELEASE CHAR ( 1 ) FOR SBCS DATA ; 
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
BEGIN 
GET DIAGNOSTICS CONDITION 1 
LOCAL_SQLCODE = DB2_RETURNED_SQLCODE , LOCAL_SQLSTATE = RETURNED_SQLSTATE , 
V_MESSAGE_TEXT = MESSAGE_TEXT ; 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: FAILED WITH SQLCODE=' CONCAT LOCAL_SQLCODE CONCAT 
' SQLSTATE=' CONCAT LOCAL_SQLSTATE CONCAT ' MESSAGE=' CONCAT 
V_MESSAGE_TEXT ; 
CALL SYSTOOLS . LPRINTF ( V_FAILURE_TEXT ) ; 
RETURN - 1 ; 
END ; 
  
SELECT COUNT ( * ) INTO ACS_JAR_COUNT FROM TABLE ( 
QSYS2 . IFS_OBJECT_STATISTICS ( '/QIBM/proddata/Access/ACS/Base/acsbundle.jar' ) ) ; 
IF ( ACS_JAR_COUNT = 0 ) THEN 
SET V_FAILURE_TEXT = 
'GENERATE_SPREADSHEET: ACS jar (/QIBM/proddata/Access/ACS/Base/acsbundle.jar) not found' ; 
SIGNAL SQLSTATE 'VSP06' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( COLUMN_HEADINGS <> 'COLUMN' ) AND ( COLUMN_HEADINGS <> 'LABEL' ) AND 
( COLUMN_HEADINGS <> 'NONE' ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: COLUMN_HEADINGS: ' CONCAT COLUMN_HEADINGS CONCAT 
' IS INVALID' ; 
SIGNAL SQLSTATE 'VSP01' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( SPREADSHEET_QUERY IS NULL ) AND 
( FILE_NAME IS NULL OR LIBRARY_NAME IS NULL ) AND 
( SPREADSHEET_QUERY_IFS IS NULL ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: SPREADSHEET_QUERY, ' CONCAT 
'SPREADSHEET_QUERY_IFS, OR LIBRARY_NAME AND FILE_NAME MUST BE SPECIFIED' ; 
SIGNAL SQLSTATE 'VSP02' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( ( SPREADSHEET_QUERY IS NOT NULL ) AND ( SPREADSHEET_QUERY_IFS IS NOT NULL ) ) OR 
( ( SPREADSHEET_QUERY IS NOT NULL ) AND ( ( FILE_NAME IS NOT NULL OR LIBRARY_NAME IS NOT NULL ) ) ) OR 
( ( SPREADSHEET_QUERY_IFS IS NOT NULL ) AND ( ( FILE_NAME IS NOT NULL OR LIBRARY_NAME IS NOT NULL ) ) ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: ONLY SPECIFY ONE OF SPREADSHEET_QUERY, ' CONCAT 
'SPREADSHEET_QUERY_IFS, OR LIBRARY_NAME AND FILE_NAME' ; 
SIGNAL SQLSTATE 'VSP05' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( SPREADSHEET_QUERY_IFS IS NOT NULL ) THEN 
SELECT COUNT ( * ) INTO IFS_FILE_COUNT 
FROM TABLE ( QSYS2 . IFS_OBJECT_STATISTICS ( SPREADSHEET_QUERY_IFS ) ) ; 
IF ( IFS_FILE_COUNT = 0 ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: SPREADSHEET_QUERY_IFS: File not found - ' 
CONCAT SPREADSHEET_QUERY_IFS ; 
SIGNAL SQLSTATE 'VSP08' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
SELECT CCSID INTO IFS_FILE_CCSID 
FROM TABLE ( QSYS2 . IFS_OBJECT_STATISTICS ( SPREADSHEET_QUERY_IFS ) ) ; 
IF ( IFS_FILE_CCSID <> 1208 ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: SPREADSHEET_QUERY_IFS: CCSID must be 1208, not ' 
CONCAT IFS_FILE_CCSID CONCAT ' for file ' CONCAT SPREADSHEET_QUERY_IFS ; 
SIGNAL SQLSTATE 'VSP09' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
END IF ; 
  
IF ( OVERWRITE IS NULL ) OR ( ( OVERWRITE <> 'REPLACE' ) AND ( OVERWRITE <> 'APPEND' ) ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: OVERWRITE: ' CONCAT 
COALESCE ( OVERWRITE , 'NULL' ) CONCAT ' IS INVALID' ; 
SIGNAL SQLSTATE 'VSP07' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( STARTING_COLUMN IS NOT NULL ) AND 
( ( SPREADSHEET_TYPE <> 'xlsx' ) AND ( SPREADSHEET_TYPE <> 'xls' ) AND ( SPREADSHEET_TYPE <> 'ods' ) ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: STARTING_COLUMN: Not allowed with spreadsheet type: ' 
CONCAT SPREADSHEET_TYPE ; 
SIGNAL SQLSTATE 'VSP10' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( STARTING_ROW IS NOT NULL ) AND 
( ( SPREADSHEET_TYPE <> 'xlsx' ) AND ( SPREADSHEET_TYPE <> 'xls' ) AND ( SPREADSHEET_TYPE <> 'ods' ) ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: STARTING_ROW: Not allowed with spreadsheet type: ' 
CONCAT SPREADSHEET_TYPE ; 
SIGNAL SQLSTATE 'VSP11' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( STARTING_SHEET IS NOT NULL ) AND 
( ( SPREADSHEET_TYPE <> 'xlsx' ) AND ( SPREADSHEET_TYPE <> 'xls' ) AND ( SPREADSHEET_TYPE <> 'ods' ) ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: STARTING_SHEET: Not allowed with spreadsheet type: ' 
CONCAT SPREADSHEET_TYPE ; 
SIGNAL SQLSTATE 'VSP12' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( OVERWRITE IS NOT NULL ) AND ( OVERWRITE = 'APPEND' ) AND 
( ( SPREADSHEET_TYPE <> 'xlsx' ) AND ( SPREADSHEET_TYPE <> 'xls' ) ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: OVERWRITE: APPEND not allowed with spreadsheet type: ' 
CONCAT SPREADSHEET_TYPE ; 
SIGNAL SQLSTATE 'VSP13' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
-- 
-- Is ACS 1.1.9.9 (or higher) applied to this IBM i? 
-- 
SET ACS_LEVEL_1199 = 0 ; 
WITH ILEVEL ( IVERSION , IRELEASE ) AS 
( 
SELECT OS_VERSION , OS_RELEASE FROM SYSIBMADM . ENV_SYS_INFO 
) 
SELECT COUNT ( * ) INTO ACS_LEVEL_1199 FROM ILEVEL , QSYS2 . PTF_INFO 
WHERE PTF_PRODUCT_ID = '5770SS1' AND 
PTF_LOADED_STATUS IN ( 'APPLIED' , 'PERMANENTLY APPLIED' , 'SUPERSEDED' ) AND 
PTF_IDENTIFIER = 
CASE WHEN IRELEASE = '6' /* IBM i 7.6 */ 
THEN 'SJ06724' 
WHEN IRELEASE = '5' /* IBM i 7.5 */ 
THEN 'SJ06723' END ; 
  
SET ACS_LEVEL_1199_PTF = 
( WITH ILEVEL ( IVERSION , IRELEASE ) AS 
( 
SELECT OS_VERSION , OS_RELEASE FROM SYSIBMADM . ENV_SYS_INFO 
) 
SELECT CASE WHEN IRELEASE = '6' /* IBM i 7.6 */ 
THEN 'SJ06724' 
WHEN IRELEASE = '5' /* IBM i 7.5 */ 
THEN 'SJ06723' END FROM ILEVEL ) ; 
  
-- 
-- Is ACS 1.1.9.8 (or higher) applied to this IBM i? 
-- 
SET ACS_LEVEL_1198 = 0 ; 
WITH ILEVEL ( IVERSION , IRELEASE ) AS 
( 
SELECT OS_VERSION , OS_RELEASE FROM SYSIBMADM . ENV_SYS_INFO 
) 
SELECT COUNT ( * ) INTO ACS_LEVEL_1198 FROM ILEVEL , QSYS2 . PTF_INFO 
WHERE PTF_PRODUCT_ID = '5770SS1' AND 
PTF_LOADED_STATUS IN ( 'APPLIED' , 'PERMANENTLY APPLIED' , 'SUPERSEDED' ) AND 
PTF_IDENTIFIER = 
CASE WHEN IRELEASE = '6' /* IBM i 7.6 */ 
THEN 'SJ04934' 
WHEN IRELEASE = '5' /* IBM i 7.5 */ 
THEN 'SJ04933' END ; 
  
SET ACS_LEVEL_1198_PTF = 
( WITH ILEVEL ( IVERSION , IRELEASE ) AS 
( 
SELECT OS_VERSION , OS_RELEASE FROM SYSIBMADM . ENV_SYS_INFO 
) 
SELECT CASE WHEN IRELEASE = '6' /* IBM i 7.6 */ 
THEN 'SJ04934' 
WHEN IRELEASE = '5' /* IBM i 7.5 */ 
THEN 'SJ04933' END FROM ILEVEL ) ; 
  
IF ( STARTING_SHEET IS NOT NULL ) AND ( ACS_LEVEL_1198 = 0 ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: STARTING_SHEET: ' CONCAT 
'requires PTF 5770SS1 ' CONCAT ACS_LEVEL_1198_PTF ; 
SIGNAL SQLSTATE 'VSP14' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( STARTING_COLUMN IS NOT NULL ) AND ( ACS_LEVEL_1198 = 0 ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: STARTING_COLUMN: ' CONCAT 
'requires PTF 5770SS1 ' CONCAT ACS_LEVEL_1198_PTF ; 
SIGNAL SQLSTATE 'VSP15' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( STARTING_ROW IS NOT NULL ) AND ( ACS_LEVEL_1198 = 0 ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: STARTING_ROW: ' CONCAT 
'requires PTF 5770SS1 ' CONCAT ACS_LEVEL_1198_PTF ; 
SIGNAL SQLSTATE 'VSP16' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( OVERWRITE IS NOT NULL ) AND ( OVERWRITE = 'APPEND' ) AND ( ACS_LEVEL_1198 = 0 ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: OVERWRITE: APPEND ' CONCAT 
'requires PTF 5770SS1 ' CONCAT ACS_LEVEL_1198_PTF ; 
SIGNAL SQLSTATE 'VSP17' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( SPREADSHEET_QUERY_IFS IS NOT NULL ) AND ( ACS_LEVEL_1199 = 0 ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: SPREADSHEET_QUERY_IFS: ' CONCAT 
'requires PTF 5770SS1 ' CONCAT ACS_LEVEL_1199_PTF ; 
SIGNAL SQLSTATE 'VSP18' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
IF ( SPREADSHEET_TYPE <> 'csv' ) AND 
( SPREADSHEET_TYPE <> 'ods' ) AND 
( SPREADSHEET_TYPE <> 'xlsx' ) AND 
( SPREADSHEET_TYPE <> 'xls' ) AND 
( SPREADSHEET_TYPE <> 'txt' ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: SPREADSHEET_TYPE: ' CONCAT SPREADSHEET_TYPE CONCAT 
' IS INVALID' ; 
SIGNAL SQLSTATE 'VSP03' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
  
SET CMD_TEXT = 'QSYS/STRQSH CMD(''/QIBM/ProdData/Java400/bin/java' ; 
IF ( SPREADSHEET_TYPE = 'xlsx' ) OR ( SPREADSHEET_TYPE = 'xls' ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' -Dcom.ibm.iaccess.dataxfer.AdjustColumns=true' ; 
END IF ; 
SET CMD_TEXT = CMD_TEXT 
CONCAT ' -jar /QIBM/proddata/Access/ACS/Base/acsbundle.jar' 
CONCAT ' /plugin=cldownload /system=localhost' 
CONCAT ' /clientfile=' CONCAT PATH_NAME CONCAT '.' CONCAT SPREADSHEET_TYPE ; 
IF ( SPREADSHEET_QUERY IS NOT NULL ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' /sql="' CONCAT REPLACE ( SPREADSHEET_QUERY , '''' , '''''' ) CONCAT '"' ; 
ELSEIF ( SPREADSHEET_QUERY_IFS IS NOT NULL ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' /sqlfile=' CONCAT SPREADSHEET_QUERY_IFS ; 
ELSE 
IF ( QSYS2 . SQL_CHECK_AUTHORITY ( LIBRARY_NAME , FILE_NAME ) = 0 ) THEN 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: INSUFFICIENT AUTHORITY OR FILE DOES NOT EXIST: ' CONCAT 
LIBRARY_NAME CONCAT '/' CONCAT FILE_NAME ; 
SIGNAL SQLSTATE 'VSP04' SET MESSAGE_TEXT = V_FAILURE_TEXT ; 
END IF ; 
SET CMD_TEXT = CMD_TEXT CONCAT ' /hostfile=' CONCAT LIBRARY_NAME CONCAT '/' CONCAT FILE_NAME ; 
END IF ; 
IF ( OVERWRITE = 'APPEND' ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' /update' ; 
END IF ; 
IF ( COLUMN_HEADINGS = 'COLUMN' ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' /colheadings=1' ; 
ELSEIF ( COLUMN_HEADINGS = 'LABEL' ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' /colheadings=1 /usecollabels' ; 
ELSE 
SET CMD_TEXT = CMD_TEXT CONCAT ' /colheadings=0' ; 
END IF ; 
IF ( STARTING_SHEET IS NOT NULL ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' /sheet=' CONCAT STARTING_SHEET ; 
END IF ; 
IF ( STARTING_ROW IS NOT NULL ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' /row=' CONCAT STARTING_ROW ; 
END IF ; 
IF ( STARTING_COLUMN IS NOT NULL ) THEN 
SET CMD_TEXT = CMD_TEXT CONCAT ' /column=' CONCAT STARTING_COLUMN ; 
END IF ; 
SET CMD_TEXT = CMD_TEXT CONCAT ''')' ; 
BEGIN 
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
BEGIN 
SET OVERRIDE_FAILURE = 1 ; 
END ; 
SELECT COUNT ( * ) INTO OVERRIDE_COUNT 
FROM SYSTOOLS . OVERRIDE_INFO 
WHERE FILE_NAME = 'STDOUT' AND TYPE = 'DB' ; 
IF ( OVERRIDE_COUNT = 0 AND OVERRIDE_FAILURE = 0 ) THEN 
SELECT COUNT ( * ) INTO FILE_EXISTS 
FROM TABLE ( QSYS2 . OBJECT_STATISTICS ( 'QTEMP' , '*FILE' , 'QGENSPREAD' ) ) ; 
IF ( FILE_EXISTS = 0 ) THEN 
DECLARE GLOBAL TEMPORARY TABLE SESSION . QGENSPREAD ( PRINT_DATA CHAR ( 133 ) ) 
WITH REPLACE ON COMMIT PRESERVE ROWS ; 
END IF ; 
IF ( OVERRIDE_FAILURE = 0 ) THEN 
CALL QSYS2 . QCMDEXC ( 'QSYS/OVRDBF FILE(STDOUT) TOFILE(QTEMP/QGENSPREAD) OVRSCOPE(*JOB)' ) ; 
END IF ; 
END IF ; 
END ; 
CALL SYSTOOLS . LPRINTF ( 'SPREADSHEET COMMAND: ' CONCAT CMD_TEXT ) ; 
CALL QSYS2 . QCMDEXC ( CMD_TEXT ) ; 
WITH LAST_QSH_MSG ( MSGSTS ) AS ( 
SELECT INTERPRET ( SUBSTR ( MESSAGE_TOKENS , 1 , 4 ) AS INTEGER ) 
FROM TABLE ( QSYS2 . JOBLOG_INFO ( '*' ) ) 
WHERE MESSAGE_ID = 'QSH0005' 
ORDER BY ORDINAL_POSITION DESC 
LIMIT 1 
) 
SELECT COUNT ( * ) INTO CLDOWNLOAD_RESULT 
FROM LAST_QSH_MSG 
WHERE MSGSTS = 0 ; 
BEGIN 
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
BEGIN 
SET OVERRIDE_FAILURE = 1 ; 
END ; 
IF ( OVERRIDE_COUNT = 0 AND OVERRIDE_FAILURE = 0 ) THEN 
CALL QSYS2 . QCMDEXC ( 'QSYS/DLTOVR FILE(STDOUT) LVL(*JOB)' ) ; 
END IF ; 
END ; 
IF ( KILL_DAEMON = 'YES' ) THEN 
SET CMD_TEXT = 'QSYS/STRQSH CMD(''/QIBM/ProdData/Java400/bin/java' 
CONCAT ' -jar /QIBM/proddata/Access/ACS/Base/acsbundle.jar' 
CONCAT ' /plugin=MAINT' 
CONCAT ' /KILLDAEMON'')' ; 
CALL QSYS2 . QCMDEXC ( CMD_TEXT ) ; 
END IF ; 
IF ( CLDOWNLOAD_RESULT = 1 ) THEN 
RETURN 1 ; 
ELSE 
SET V_FAILURE_TEXT = 'GENERATE_SPREADSHEET: ACS - cldownload FAILED - CONSULT JOBLOG FOR DETAILS' ; 
CALL SYSTOOLS . LPRINTF ( V_FAILURE_TEXT ) ; 
RETURN - 1 ; 
END IF ; 
END  ; 
  
COMMENT ON SPECIFIC FUNCTION SYSTOOLS.GENSPREAD 
	IS 'DB2 FOR IBM i SUPPLIED OBJECT VERSION 07500020001' ; 
  
COMMENT ON PARAMETER SPECIFIC FUNCTION SYSTOOLS.GENSPREAD 
( PATH_NAME IS 'pathname - Default: none' , 
	SPREADSHEET_QUERY IS 'string - Default: NULL' , 
	LIBRARY_NAME IS 'name - Default: NULL' , 
	FILE_NAME IS 'name - Default: NULL' , 
	SPREADSHEET_TYPE IS 'csv, ods, txt, xls, xlsx - Default: csv' , 
	COLUMN_HEADINGS IS 'COLUMN, LABEL, NONE - Default: NONE' , 
	SPREADSHEET_QUERY_IFS IS 'pathname - Default: NULL' , 
	OVERWRITE IS 'APPEND, REPLACE - Default: REPLACE' , 
	STARTING_SHEET IS 'number - Default: NULL' , 
	STARTING_ROW IS 'number - Default: NULL' , 
	STARTING_COLUMN IS 'string - Default: NULL' , 
	KILL_DAEMON IS 'NO, YES - Default: NO' ) ; 
  
GRANT EXECUTE   
ON SPECIFIC FUNCTION SYSTOOLS.GENSPREAD 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC FUNCTION SYSTOOLS.GENSPREAD 
TO QSYS WITH GRANT OPTION ; 
  
